version: '2'
services:
  nginx-proxy:
    build: .
    image: sinmax/nginx-proxy:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"
    volumes:
      - "./proxy.sh:/proxy.sh"
      - "./conf:/proxy"
      - "./nginx:/etc/nginx/snippets"
      - ".nginx-conf.d:/etc/nginx/conf.d"
      - "./ssl/nginx-certs:/etc/nginx/certs"
      - "./ssl/letsencrypt:/etc/letsencrypt"
      - "./logs/nginx:/var/log/nginx"
      - "./logs/letsencrypt:/var/log/letsencrypt"
      - "./www:/usr/share/nginx/html"
